/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_atexit_include_h__
#define _mulle_atexit_include_h__

// You can tweak the following #include with these commands.
// (Use 2DAC666A-AD85-4036-82EF-C0A7E45DCF1D instead of mulle-thread if there are duplicate entries)
//    remove:             `mulle-sde dependency mark mulle-thread no-header`
//    rename:             `mulle-sde dependency|library set mulle-thread include whatever.h`
//    reorder:            `mulle-sde dependency move mulle-thread <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-thread [no-]import`
//    toggle public:      `mulle-sde dependency mark mulle-thread [no-]public`
//    toggle optional:    `mulle-sde dependency mark mulle-thread [no-]require`
//    remove for platform:`mulle-sde dependency mark mulle-thread no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-thread/mulle-thread.h>   // mulle-thread

#endif
